spring:
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 256MB
      max-file-size: 256MB
  data:
    mongodb:
      database: Blog
      uri: ${BT_MONGODB_URI}
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: 'smtp.gmail.com'
    username:  ${BT_SMTP_EMAIL}
    password: ${BT_GMAIL_SMTP_PASSWORD}
    port: '587'
    templates:
      path: mail-templates
  datasource:
    url: ${BT_AWS_POSTGRESSQL_URL}
    username: postgres
    password: ${BT_AWS_POSTGRESSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
    ssl-mode: require
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
user:
  email:
    from: ${BT_USER_EMAIL_FROM}
management:
  endpoints:
    web:
      exposure:
        include: '*'
frontend:
  url: ${BT_FRONTEND_URL} 
blog:
  client:
    secret: ${BT_BLOG_CLIENT_SECRET}
  auth:
    secret: ${BT_BLOG_AUTH_SECRET}
user:
  default:
    password: ${BT_USER_DEFAULT_PASSWORD}
